u=input("enter a number:")
print(u)
a=input(("this value 64 can float "))
print((a))
x=int(input(748))
print(x)
c=input("the value of c is 63: ")
d=input("the value of d is 32: ")
print(c*d)
s=input("the value  of s is 85:")
w=input("the value of w is srushti:")
print(int(s)+str(w))
p=int(input("solider"))
print(input)
